export enum QuestionCategory {
  SCIENCE = "SCIENCE",
  HISTORY = "HISTORY",
  LIFEMOMENTS = "LIFEMOMENTS",
  PERSONAL = "PERSONAL",
  DECISIONS = "DECISIONS",
  HYPOTHETICAL = "HYPOTHETICAL",
  DAILY_LIFE = "DAILY_LIFE",
  PHILOSOPHICAL = "PHILOSOPHICAL",
  ABSURD = "ABSURD",
  RELATIONSHIPS = "RELATIONSHIPS",
  JOB = "JOB",
  FOOD_DRINK = "FOOD_DRINK",
}
